### ISSUE TITLE
Why default auth and auth hooks isn't available?

### ISSUE THREAD

**Issue by eadenink** [maka-io/maka-rest#10]
In the code of package `MakaRest.auth` have empty auth hooks functions and `loginType: null` that can't be set within constructor while `initializeDefaultAuthEndpoints` function requires `loginType: 'default'` value to create default auth endpoints

**Comment by maka-io** [comment]
hey @eadenink ! If I am understanding your question correctly (and sorry if I'm not), the need to specify `loginType: 'default'` is to prevent different types of login mechanisms within the same MakaRest instance.  Further, the auth endpoints has been moved off the constructor to prevent multiple constructors from creating colliding initializations (currently present in the original Restivus).

Does that help?

**Comment by maka-io** [comment]
Try use the hooks that are attached to the `auth` property:
```javascript
MakaRest.auth.loginType = 'default';

MakaRest.auth.onLoggedIn = ({ request, user }) => { };

MakaRest.auth.onLoginFailure = ({ request, bodyParams }) => {};

MakaRest.auth.onLoggedOut = ({ request, user }) => {};
```
