### ISSUE TITLE
GetAll paging?

### ISSUE THREAD

**Issue by allenfuller** [maka-io/maka-rest#11]
This library looks great and excited to look into it more. 

With GetAll, is there a paging function, i.e. only returns 25 items at a time, or would that be something we would just add inside the route action?

**Comment by maka-io** [comment]
Hey @allenfuller ! Thanks for taking the time to check out this library!

Much apologies, I adapted this project from Restivus and have not updated the documentation completely enough.  This package no longer supports the `addCollection` method like Restivus.  It was adding a lot of confusion in every project I ever used it in.  

So as far as the GetAll method, you'd need to add that in the `addRoute` and add it to your data model access.

I've updated the README a little to no longer show that feature.  Again, apologies!

**Comment by allenfuller** [comment]
Awesome, thanks!
