### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by freeseamew** [maka-io/maka-rest#3]
Currently using version 2.2 of the meter.

An error occurs when logging into rest api as follows.

```
curl http://localhost:3000/api/login/ -d "username=MyId.com&password=myPassword"
```

The error contents are as follows.

```

"Error attempting login"
```

The default settings are as follows.

```

import { Restivus } from 'meteor/maka:rest';


Items = new Mongo.Collection('items');
Articles = new Mongo.Collection('articles');

if (Meteor.isServer) {
  // Global API configuration
  const Api = new Restivus({
    useDefaultAuth: true,
    prettyJson: true,
    auth: {
      token: 'auth.apiKey',
      user: function () {
        return {
          userId: this.request.headers['user-id'],
          token: this.request.headers['login-token']
        };
      }
    },
    defaultHeaders: {
      'Content-Type': 'application/json'
    },
    onLoggedIn() {
      console.log(this.user.username + ' (' + this.userId + ') logged in');
    },
    onLoggedOut() {
      console.log(this.user.username + ' (' + this.userId + ') logged out');
    },    
  });

  // Generates: GET, POST on /api/items and GET, PUT, PATCH, DELETE on
  // /api/items/:id for the Items collection
  Api.addCollection(Items);

  // Generates: POST on /api/users and GET, DELETE /api/users/:id for
  // Meteor.users collection
  Api.addCollection(Meteor.users, {
    excludedEndpoints: ['getAll', 'put'],
    routeOptions: {
      authRequired: true
    },
    endpoints: {
      post: {
        authRequired: false
      },
      delete: {
        roleRequired: 'admin'
      }
    }
  });

  // Maps to: /api/articles/:id
  Api.addRoute('articles/:id', {authRequired: true}, {
    get() {
      return Articles.findOne(this.urlParams.id);
    },
    delete: {
      roleRequired: ['author', 'admin'],
      action() {
        if (Articles.remove(this.urlParams.id)) {
          return {status: 'success', data: {message: 'Article removed'}};
        }
        return {
          statusCode: 404,
          body: {status: 'fail', message: 'Article not found'}
        };
      }
    }
  });
}

```
Please give us a hint.

**Comment by maka-io** [comment]
Good morning, 
Just at first glance, I see your username is kind of a url.  Can you confirm that is your intended workflow?

**Comment by freeseamew** [comment]
The curls actually used are as follows.

```
curl http://localhost:3000/api/login/ -d "username=admin@admin.com&password=1234"

```
And before I started running the server, I added and ran an email user named admin@admin.com

**Comment by maka-io** [comment]
gotcha, could you try this:

```
curl http://localhost:3000/api/login -d "email=admin@admin.com&password=1234"
```

**Comment by freeseamew** [comment]
Thank you. I changed username to email and it became a normal login.

and I have more question. If I run the parmas with email and password on 'postman' instead of curl, I still get the error "Errorattempting login". Which part will be the problem in this part?

And the authToken returned after logging in.

```
{
  "authToken": "Eb7fyKQMBRH06OhNGmAJQEV0lIHvYJDYimn20OT2qzQ",
  "userId": "3zBHizraGPWNyi9qW",
  "when": "2021-07-13T15:45:40.423Z"
}

```
Why is this part of the users' hashedToken differently different?

```
{
    "_id" : "3zBHizraGPWNyi9qW",
    "createdAt" : ISODate("2021-07-13T07:47:56.090Z"),
    "services" : {
        "password" : {
            "bcrypt" : "$2b$10$06HgXvNEksfGX3.sLYTTCOMpHId1LvRQBXPLxhAzChwc8xdyXuOPm"
        },
        "resume" : {
            "loginTokens" : [ 
                {
                    "hashedToken" : "QqfvY/tFgNo71eRltmn/RCpVz8Kw6ovhB2rWgdGX41w="
                }
            ]
        }
    },
    "emails" : [ 
        {
            "address" : "admin@admin.com",
            "verified" : true
        }
    ]
}
```

**Comment by maka-io** [comment]
Great!  As far as Postman, just make sure you have the HTTP type set to POST rather than GET.  curl will default automatically to POST if it sees the data argument (-d) being used. I don't believe Postman does that.

The authToken would be tied to the loginTokens, just note that they won't be the same because of how the sha256 asymmetric encryption works.  But if you delete that loginToken from the user, you'll notice that that token becomes invalid.

**Comment by freeseamew** [comment]
Thanks!! 

And when logged in, it returns as follows:

```
{
  "authToken": "ANMAugVzxG01brf-X9PGCyGzrNcU7hq9oCAkVJIQ7RZ",
  "userId": "3zBHizraGPWNyi9qW",
  "when": "2021-07-13T16:29:53.263Z"
}

```
If you log out as follows, you will get an Unauthorized error.

```
curl http://localhost:3000/api/logout -X POST -H "X-Auth-Token: ANMAugVzxG01brf-X9PGCyGzrNcU7hq9oCAkVJIQ7RZ" 
```

Please help me with this part too.

**Comment by maka-io** [comment]
Well there is a bug! I'm looking for 'x-auth-token' rather than 'X-Auth-Token' ... so I'm not correctly getting that header.  I'll fix that, but in the mean time, try using 'x-auth-token'

**Comment by maka-io** [comment]
This is now fixed in version 2.0.7:
https://github.com/maka-io/maka-rest/commit/c6f90400441d440dec20bca017869668f661d01a

**Comment by freeseamew** [comment]
Thank you for the quick correction.

I tested the new version.

But there's still an 'Unauthorized' error.


```

curl http://localhost:3000/api/login/ -d "email=admin@admin.com&password=1234"

...

{
  "authToken": "qh8iX6yH6nvwj8X5l4BzMQJVgcbNkJDPF4M1Fgaa8v4",
  "userId": "TAkphdBgnk5tzg7JM",
  "when": "2021-07-14T02:35:34.494Z"
}

...

url http://localhost:3000/api/logout -X POST -H "X-Auth-Token: qh8iX6yH6nvwj8X5l4BzMQJVgcbNkJDPF4M1Fgaa8v4" 

...

"Unauthorized"

```
And one more qustion 

When I logout as postman,

Is it right to send X-Auth-Token to the header?

**Comment by maka-io** [comment]
Sorry for the delay here, I just gave it a shot with version 2.0.7 and it was successful:

```
{
  "authToken": "q6M2UOO6LEqkbEmQpWhokPp-CqTukLwoxuSpHNIdNho",
  "userId": "T3jwTa62snifJhTAg",
  "when": "2021-07-16T11:43:57.366Z"
}
```

```
curl http://localhost:4000/api/v1/logout -X POST -H 'X-Auth-Token: q6M2UOO6LEqkbEmQpWhokPp-CqTukLwoxuSpHNIdNho'

"KTHXBYE!"
```

Can you confirm that your using 2.0.7?

As for Postman, yes you do need the X-Auth-Token in the header for logout.

**Comment by freeseamew** [comment]
Sorry it seems to be a bug to my code.
Thanks it worked out well.
Thank you. :)

**Comment by maka-io** [comment]
Terrific! Please let me know if you need anything else :)
