### ISSUE TITLE
cors errors

### ISSUE THREAD

**Issue by freeseamew** [maka-io/maka-rest#4]
There is a cors-related error.

Get, post works fine.

But In the case of delete and put, the browser is experiencing the following cors error:

The header is set as follows by default.

```
  const Api = new Restivus({
    prettyJson: true,
    useDefaultAuth: true,
    enableCors: true,
    enableCors: true,
    defaultHeaders: {
       'Access-Control-Allow-Origin': '*',
       'Access-Control-Allow-Headers': 'Origin',
       'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
       "Access-Control-Allow-Credentials": true ,
       'Content-Type': 'application/json',
       'Access-Control-Max-Age': '86400',
    },

  });

```

The router was set up as follows:

```
    Api.addRoute('article/:_id', {authRequired:false}, {
    get: {
      action() {
        console.log('get article')
        return articles.readOneArticle(this.urlParams._id);
      }
    },
    delete: {
      async action() {
        console.log('delete article');
    
        values = {
          _id: this.urlParams._id,
          userId: this.userId
        }
        const result = await articles.removeArticle(values);
        return result;
      },    
    },
  })

```
And the message on the browser is as follows.

```
Access to XMLHttpRequest at 'http://localhost:3000/api/article/xkSCBHQQkrWbPBsXL' from origin 'http://localhost:5000' has been blocked by CORS policy: Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.
```

Please give me a hint to solve it.

**Comment by freeseamew** [comment]
The following is a link to the test source:

https://github.com/freeseamew/maka_rest_test

'get', 'post' works fine. but 'put', 'delete' don't work.

**Comment by maka-io** [comment]
Good afternoon! Sorry for the late reply.  I'll check in on this and see if I can resolve this issue for you.

**Comment by maka-io** [comment]
Again, sorry for the late reply! I've resolve this issue in version 2.0.9 (just released!). Please let me know if your issue has been solved. :)

**Comment by freeseamew** [comment]
Thank you. Thanks to you, it worked out well. Have a nice weekend :)
