### ISSUE TITLE
Can we make '\n\r' optional?

### ISSUE THREAD

**Issue by AlekseyMalyshev** [maka-io/maka-rest#5]
We have issues because of those two characters added to plain text body response - '\n\r'. Is it possible to make it optional? Are you OK if I make a PR?

**Comment by maka-io** [comment]
Hey @AlekseyMalyshev ! You sure can, and I'm not opposed to removing them completely.

**Comment by AlekseyMalyshev** [comment]
@maka-io OK, I removed it then. I think it should have been '\r\n' anyway, not '\n\r'.
Please merge https://github.com/maka-io/maka-rest/pull/6/commits

**Comment by maka-io** [comment]
@AlekseyMalyshev , thank you for your PR! It has been merged, and the changes published.

:)
