### ISSUE TITLE
ReferenceError: response is not defined in onLoggedIn

### ISSUE THREAD

**Issue by kirohuji** [maka-io/maka-rest#7]
I want to add additional return results in onLoggedIn Function, but I reported an error.

<img width="758" alt="D087803C-7EB9-42D6-9A29-0AF41D57D5EB" src="https://user-images.githubusercontent.com/20853437/160045057-8b497bd7-1038-4ecd-827e-6fcd28f972fa.png">

<img width="1072" alt="03B30606-5EC2-46D3-88F3-4FF0F6DEF659" src="https://user-images.githubusercontent.com/20853437/160045049-57e7ac55-4c68-44b3-bb35-dd76e7374145.png">

**Comment by maka-io** [comment]
Hey @kirohuji ! Let me take a look at that and I'll get back to you.

**Comment by maka-io** [comment]
Fixed in #8 

Thank you for finding this! 🙏
